// Represents a single section
// The save file is split into two *blocks*,
// which are each consisted of 14 sections.
//
// Each section stores different data, depending on the
// section id.
//
// 0x0000 	3968 	Data
// 0x0FF4 	2 	Section ID
// 0x0FF6 	2 	Checksum
// 0x0FF8 	4 	Signature
// 0x0FFC 	4 	Save index
#[derive(Copy, Clone, Debug)]
pub struct Section {
    pub data: [u8; 3968],
    pub id: u16,
    // TODO: checksum will not be verified from save game data.
    // on write, checksum will be generated
    pub checksum: u16,
    pub signature: u32,
    pub save_index: u32,
}

impl Default for Section {
    fn default() -> Self {
        Section {
            data: [0u8; 3968],
            id: 0,
            checksum: 0,
            signature: 0,
            save_index: 0,
        }
    }
}

impl From<&[u8]> for Section {
    fn from(value: &[u8]) -> Self {
        assert!(
            value.len() == 4096,
            "Section: Length of buffer must be 4096!"
        );

        let mut data = [0u8; 3968];
        data.copy_from_slice(&value[0..3968]);

        let id = u16::from_le_bytes(value[0x0FF4..0x0FF6].try_into().unwrap());
        let checksum = u16::from_le_bytes(value[0x0FF6..0x0FF8].try_into().unwrap());
        let signature = u32::from_le_bytes(value[0x0FF8..0x0FFC].try_into().unwrap());
        let save_index = u32::from_le_bytes(value[0x0FFC..0x1000].try_into().unwrap());

        Self {
            data,
            id,
            checksum,
            signature,
            save_index,
        }
    }
}

impl Section {
    // Used to validate the integrity of saved data.
    //
    // A 16-bit checksum generated by adding up bytes from the section. The algorithm is as follows:
    //
    //     Initialize a 32-bit checksum variable to zero.
    //     Read 4 bytes at a time as 32-bit word (little-endian) and add it to the variable. The number of bytes to process in this manner is determined by Section ID.
    //     Take the upper 16 bits of the result, and add them to the lower 16 bits of the result.
    //     This new 16-bit value is the checksum.
    pub fn compute_checksum(&self) -> u16 {
        let checksum = match self
            .data
            .chunks_exact(4)
            .map(|chunk| {
                let x = u32::from_le_bytes(chunk.try_into().unwrap());
                // println!("0x{:04X}", x);
                x
            })
            .reduce(|acc, e| acc.wrapping_add(e))
        {
            Some(checksum) => checksum,
            None => panic!("Section: checksum iterator is empty"),
        };

        let upper = (checksum >> 16) as u16;
        let lower = (checksum & 0xFFFF) as u16;

        upper.wrapping_add(lower)
    }
}
